# Generated by Django 4.0.6 on 2022-11-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=80)),
                ('accountno', models.IntegerField(max_length=40)),
                ('accountname', models.CharField(max_length=50)),
            ],
        ),
    ]
